# Generated by Django 3.2.9 on 2021-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='pinterest.Categories'),
        ),
        migrations.AlterField(
            model_name='series',
            name='categories',
            field=models.ManyToManyField(to='pinterest.Categories'),
        ),
    ]
